// PERGUNTAS — FISICA
// Substitui as perguntas de exemplo pelas reais quando receberes o questionário

var perguntasFisica = {{
  nivel1: [
    {{ tipo: 'vf', pergunta: 'Pergunta VF exemplo 1 — FISICA.', resposta: true }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF exemplo 2 — FISICA.', resposta: false }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF exemplo 3 — FISICA.', resposta: true }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF exemplo 4 — FISICA.', resposta: false }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF exemplo 5 — FISICA.', resposta: true }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF exemplo 6 — FISICA.', resposta: true }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF exemplo 7 — FISICA.', resposta: false }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF exemplo 8 — FISICA.', resposta: true }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF exemplo 9 — FISICA.', resposta: false }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF exemplo 10 — FISICA.', resposta: true }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC exemplo 1 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 0 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC exemplo 2 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 1 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC exemplo 3 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 2 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC exemplo 4 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 3 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC exemplo 5 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 0 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC exemplo 6 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 1 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC exemplo 7 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 2 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC exemplo 8 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 3 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC exemplo 9 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 0 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC exemplo 10 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 1 }},
  ],
  nivel2: [
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao dissertiva exemplo 1 — FISICA.', resposta: true }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao dissertiva exemplo 2 — FISICA.', resposta: false }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao dissertiva exemplo 3 — FISICA.', resposta: true }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao dissertiva exemplo 4 — FISICA.', resposta: false }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao dissertiva exemplo 5 — FISICA.', resposta: true }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao dissertiva exemplo 6 — FISICA.', resposta: false }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao dissertiva exemplo 7 — FISICA.', resposta: true }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao dissertiva exemplo 8 — FISICA.', resposta: false }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao dissertiva exemplo 9 — FISICA.', resposta: true }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao dissertiva exemplo 10 — FISICA.', resposta: false }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF nivel 2 exemplo 1 — FISICA.', resposta: true }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF nivel 2 exemplo 2 — FISICA.', resposta: false }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF nivel 2 exemplo 3 — FISICA.', resposta: true }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 2 exemplo 1 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 0 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 2 exemplo 2 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 1 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 2 exemplo 3 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 2 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 2 exemplo 4 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 3 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 2 exemplo 5 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 0 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 2 exemplo 6 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 1 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 2 exemplo 7 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 2 }},
  ],
  nivel3: [
    {{ tipo: 'ligacao', pergunta: 'Liga os conceitos as definicoes:', colunaA: ['Conceito 1', 'Conceito 2', 'Conceito 3', 'Conceito 4'], colunaB: ['Definicao A', 'Definicao B', 'Definicao C', 'Definicao D'], resposta: [0, 1, 2, 3] }},
    {{ tipo: 'ligacao', pergunta: 'Liga os termos aos significados:', colunaA: ['Termo 1', 'Termo 2', 'Termo 3', 'Termo 4'], colunaB: ['Significado A', 'Significado B', 'Significado C', 'Significado D'], resposta: [0, 1, 2, 3] }},
    {{ tipo: 'ligacao', pergunta: 'Liga os elementos as categorias:', colunaA: ['Elemento 1', 'Elemento 2', 'Elemento 3', 'Elemento 4'], colunaB: ['Categoria A', 'Categoria B', 'Categoria C', 'Categoria D'], resposta: [0, 1, 2, 3] }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao nivel 3 exemplo 1 — FISICA.', resposta: true }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao nivel 3 exemplo 2 — FISICA.', resposta: false }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao nivel 3 exemplo 3 — FISICA.', resposta: true }},
    {{ tipo: 'dissertiva', pergunta: 'Afirmacao nivel 3 exemplo 4 — FISICA.', resposta: false }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 3 exemplo 1 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 0 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 3 exemplo 2 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 1 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 3 exemplo 3 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 2 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 3 exemplo 4 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 3 }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF nivel 3 exemplo 1 — FISICA.', resposta: true }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF nivel 3 exemplo 2 — FISICA.', resposta: false }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF nivel 3 exemplo 3 — FISICA.', resposta: true }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF nivel 3 exemplo 4 — FISICA.', resposta: false }},
    {{ tipo: 'vf', pergunta: 'Pergunta VF nivel 3 exemplo 5 — FISICA.', resposta: true }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 3 exemplo 5 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 0 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 3 exemplo 6 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 1 }},
    {{ tipo: 'mc', pergunta: 'Pergunta MC nivel 3 exemplo 7 — FISICA?', opcoes: ['Opcao A', 'Opcao B', 'Opcao C', 'Opcao D'], resposta: 2 }},
  ]
}};
